/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kaimbe.guidemo;

/**
 * 
 * @author Matthew
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		displayScrollPane = new javax.swing.JScrollPane();
		display = new javax.swing.JTextArea();
		keypad = new javax.swing.JPanel();
		keypad_1 = new javax.swing.JButton();
		keypadCancel = new javax.swing.JButton();
		keypadEnter = new javax.swing.JButton();
		keypad_2 = new javax.swing.JButton();
		keypad_3 = new javax.swing.JButton();
		keypad_4 = new javax.swing.JButton();
		keypad_5 = new javax.swing.JButton();
		keypad_6 = new javax.swing.JButton();
		keypad_7 = new javax.swing.JButton();
		keypad_8 = new javax.swing.JButton();
		keypad_0 = new javax.swing.JButton();
		keypad_9 = new javax.swing.JButton();
		keypadClear = new javax.swing.JButton();
		cardReaderPanel = new javax.swing.JPanel();
		cardReaderLabel = new javax.swing.JLabel();
		cardReaderField = new javax.swing.JTextField();
		cardReaderEnter = new javax.swing.JButton();
		receiptPrinterPanel = new javax.swing.JPanel();
		receiptPrinterLabel = new javax.swing.JLabel();
		receiptPrinterScrollPane = new javax.swing.JScrollPane();
		receiptPrinter = new javax.swing.JTextArea();
		cashDispenserPanel = new javax.swing.JPanel();
		cashDispenserLabel = new javax.swing.JLabel();
		cashDispenser = new javax.swing.JLabel();
		depositSlotPanel = new javax.swing.JPanel();
		depositSlotLabel = new javax.swing.JLabel();
		depositSlotField = new javax.swing.JTextField();
		depositSlotEnter = new javax.swing.JButton();
		maintenancePanel = new javax.swing.JPanel();
		maintenancePanelLabel = new javax.swing.JLabel();
		atmSwitchButton = new javax.swing.JButton();
		maintenancePanelField = new javax.swing.JTextField();
		maintenancePanelDescription = new javax.swing.JLabel();
		maintenancePanelState = new javax.swing.JLabel();
		titleLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("ATM Simulation");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setMaximumSize(new java.awt.Dimension(1000, 1000));
		setMinimumSize(new java.awt.Dimension(200, 200));
		setName("mainFrame"); // NOI18N
		setResizable(false);

		mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		display.setEditable(false);
		display.setBackground(new java.awt.Color(0, 0, 0));
		display.setColumns(20);
		display.setForeground(new java.awt.Color(0, 255, 0));
		display.setRows(5);
		display.setCaretColor(new java.awt.Color(0, 204, 0));
		display.setSelectedTextColor(new java.awt.Color(153, 255, 153));
		display.setSelectionColor(new java.awt.Color(0, 102, 0));
		displayScrollPane.setViewportView(display);

		keypad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		keypad_1.setText("1");
		keypad_1.setToolTipText("");
		keypad_1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_1ActionPerformed(evt);
			}
		});

		keypadCancel.setText("CANCEL");
		keypadCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypadCancelActionPerformed(evt);
			}
		});

		keypadEnter.setText("ENTER");
		keypadEnter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypadEnterActionPerformed(evt);
			}
		});

		keypad_2.setText("2");
		keypad_2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_2ActionPerformed(evt);
			}
		});

		keypad_3.setText("3");
		keypad_3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_3ActionPerformed(evt);
			}
		});

		keypad_4.setText("4");
		keypad_4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_4ActionPerformed(evt);
			}
		});

		keypad_5.setText("5");
		keypad_5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_5ActionPerformed(evt);
			}
		});

		keypad_6.setText("6");
		keypad_6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_6ActionPerformed(evt);
			}
		});

		keypad_7.setText("7");
		keypad_7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_7ActionPerformed(evt);
			}
		});

		keypad_8.setText("8");
		keypad_8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_8ActionPerformed(evt);
			}
		});

		keypad_0.setText("0");
		keypad_0.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_0ActionPerformed(evt);
			}
		});

		keypad_9.setText("9");
		keypad_9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypad_9ActionPerformed(evt);
			}
		});

		keypadClear.setText("CLEAR");
		keypadClear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				keypadClearActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout keypadLayout = new javax.swing.GroupLayout(
				keypad);
		keypad.setLayout(keypadLayout);
		keypadLayout
				.setHorizontalGroup(keypadLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								keypadLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												keypadLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																keypadLayout
																		.createSequentialGroup()
																		.addComponent(
																				keypad_7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				55,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				keypad_8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				55,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				keypad_9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				55,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																keypadLayout
																		.createSequentialGroup()
																		.addComponent(
																				keypad_0,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				55,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				keypadEnter,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																keypadLayout
																		.createSequentialGroup()
																		.addGroup(
																				keypadLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								keypadLayout
																										.createSequentialGroup()
																										.addComponent(
																												keypad_1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												55,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												keypad_2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												55,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												keypad_3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												55,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								keypadLayout
																										.createSequentialGroup()
																										.addComponent(
																												keypad_4,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												55,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												keypad_5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												55,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												keypad_6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												55,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								keypadLayout
																										.createSequentialGroup()
																										.addComponent(
																												keypadCancel,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												87,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												keypadClear,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												84,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		keypadLayout
				.setVerticalGroup(keypadLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								keypadLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												keypadLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(keypad_1)
														.addComponent(keypad_2)
														.addComponent(keypad_3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												keypadLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(keypad_4)
														.addComponent(keypad_5)
														.addComponent(keypad_6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												keypadLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(keypad_7)
														.addComponent(keypad_8)
														.addComponent(keypad_9))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												keypadLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(keypad_0)
														.addComponent(
																keypadEnter))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												keypadLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																keypadCancel)
														.addComponent(
																keypadClear))
										.addContainerGap()));

		cardReaderPanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		cardReaderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		cardReaderLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		cardReaderLabel.setText("CARD READER");

		cardReaderField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		cardReaderField.setText("Please enter your card number");

		cardReaderEnter.setText("ENTER");
		cardReaderEnter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cardReaderEnterActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout cardReaderPanelLayout = new javax.swing.GroupLayout(
				cardReaderPanel);
		cardReaderPanel.setLayout(cardReaderPanelLayout);
		cardReaderPanelLayout
				.setHorizontalGroup(cardReaderPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								cardReaderPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												cardReaderPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																cardReaderLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																cardReaderField))
										.addContainerGap())
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								cardReaderPanelLayout.createSequentialGroup()
										.addGap(108, 108, 108)
										.addComponent(cardReaderEnter)
										.addGap(108, 108, 108)));
		cardReaderPanelLayout
				.setVerticalGroup(cardReaderPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								cardReaderPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(cardReaderLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												cardReaderField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cardReaderEnter)
										.addContainerGap()));

		receiptPrinterPanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		receiptPrinterLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		receiptPrinterLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		receiptPrinterLabel.setText("RECEIPT PRINTER");

		receiptPrinter.setEditable(false);
		receiptPrinter.setColumns(20);
		receiptPrinter.setLineWrap(true);
		receiptPrinter.setRows(5);
		receiptPrinter.setToolTipText("");
		receiptPrinterScrollPane.setViewportView(receiptPrinter);

		javax.swing.GroupLayout receiptPrinterPanelLayout = new javax.swing.GroupLayout(
				receiptPrinterPanel);
		receiptPrinterPanel.setLayout(receiptPrinterPanelLayout);
		receiptPrinterPanelLayout
				.setHorizontalGroup(receiptPrinterPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								receiptPrinterPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												receiptPrinterPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																receiptPrinterScrollPane)
														.addComponent(
																receiptPrinterLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		receiptPrinterPanelLayout
				.setVerticalGroup(receiptPrinterPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								receiptPrinterPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(receiptPrinterLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												receiptPrinterScrollPane,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												0, Short.MAX_VALUE)
										.addContainerGap()));

		cashDispenserPanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());
		cashDispenserPanel.setPreferredSize(new java.awt.Dimension(175, 101));

		cashDispenserLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		cashDispenserLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		cashDispenserLabel.setText("CASH DISPENSER");

		cashDispenser.setBackground(new java.awt.Color(153, 153, 153));
		cashDispenser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		cashDispenser.setMaximumSize(new java.awt.Dimension(150, 40));
		cashDispenser.setMinimumSize(new java.awt.Dimension(150, 40));
		cashDispenser.setPreferredSize(new java.awt.Dimension(150, 40));

		javax.swing.GroupLayout cashDispenserPanelLayout = new javax.swing.GroupLayout(
				cashDispenserPanel);
		cashDispenserPanel.setLayout(cashDispenserPanelLayout);
		cashDispenserPanelLayout
				.setHorizontalGroup(cashDispenserPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								cashDispenserPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												cashDispenserPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																cashDispenserLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																cashDispenser,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																151,
																Short.MAX_VALUE))
										.addContainerGap()));
		cashDispenserPanelLayout.setVerticalGroup(cashDispenserPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						cashDispenserPanelLayout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(cashDispenserLabel)
								.addGap(18, 18, 18)
								.addComponent(cashDispenser,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(75, 75, 75)));

		depositSlotPanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());
		depositSlotPanel.setPreferredSize(new java.awt.Dimension(175, 110));

		depositSlotLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		depositSlotLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		depositSlotLabel.setText("DEPOSIT SLOT");

		depositSlotField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		depositSlotField.setText("Please enter an amount");

		depositSlotEnter.setText("ENTER");
		depositSlotEnter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				depositSlotEnterActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout depositSlotPanelLayout = new javax.swing.GroupLayout(
				depositSlotPanel);
		depositSlotPanel.setLayout(depositSlotPanelLayout);
		depositSlotPanelLayout
				.setHorizontalGroup(depositSlotPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								depositSlotPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												depositSlotPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																depositSlotLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																depositSlotField))
										.addContainerGap())
						.addGroup(
								depositSlotPanelLayout.createSequentialGroup()
										.addGap(53, 53, 53)
										.addComponent(depositSlotEnter)
										.addGap(53, 53, 53)));
		depositSlotPanelLayout
				.setVerticalGroup(depositSlotPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								depositSlotPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(depositSlotLabel)
										.addGap(18, 18, 18)
										.addComponent(
												depositSlotField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(depositSlotEnter)
										.addGap(61, 61, 61)));

		javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(
				mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		mainPanelLayout
				.setHorizontalGroup(mainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								mainPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												mainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																mainPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				keypad,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				cashDispenserPanel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				depositSlotPanel,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																mainPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				displayScrollPane,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				272,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				mainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								receiptPrinterPanel,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								cardReaderPanel,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))))
										.addContainerGap()));
		mainPanelLayout
				.setVerticalGroup(mainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								mainPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												mainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																mainPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				cardReaderPanel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				receiptPrinterPanel,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(
																displayScrollPane,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																213,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												mainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																cashDispenserPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																165,
																Short.MAX_VALUE)
														.addComponent(
																keypad,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																depositSlotPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																165,
																Short.MAX_VALUE))
										.addContainerGap()));

		maintenancePanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		maintenancePanelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		maintenancePanelLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		maintenancePanelLabel.setText("MAINTENANCE PANEL");

		atmSwitchButton.setText("TURN ON");
		atmSwitchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				atmSwitchButtonActionPerformed(evt);
			}
		});

		maintenancePanelField
				.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		maintenancePanelDescription
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		maintenancePanelDescription
				.setText("<html>Please enter the amount of $20 bills <br> in the cash dispenser. </html>");

		maintenancePanelState
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout maintenancePanelLayout = new javax.swing.GroupLayout(
				maintenancePanel);
		maintenancePanel.setLayout(maintenancePanelLayout);
		maintenancePanelLayout
				.setHorizontalGroup(maintenancePanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								maintenancePanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												maintenancePanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																maintenancePanelLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																maintenancePanelDescription)
														.addComponent(
																maintenancePanelField)
														.addComponent(
																maintenancePanelState,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap())
						.addGroup(
								maintenancePanelLayout.createSequentialGroup()
										.addGap(71, 71, 71)
										.addComponent(atmSwitchButton)
										.addGap(71, 71, 71)));
		maintenancePanelLayout
				.setVerticalGroup(maintenancePanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								maintenancePanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(maintenancePanelLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												maintenancePanelState,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												20,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												maintenancePanelDescription,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												maintenancePanelField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(atmSwitchButton)
										.addGap(241, 241, 241)));

		titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLabel.setText("ATM SIMULATION");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														titleLabel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		mainPanel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		maintenancePanel,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(titleLabel)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														mainPanel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														maintenancePanel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cardReaderEnterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cardReaderEnterActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cardReaderEnterActionPerformed

	private void atmSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_atmSwitchButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_atmSwitchButtonActionPerformed

	private void depositSlotEnterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_depositSlotEnterActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_depositSlotEnterActionPerformed

	private void keypad_1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_1ActionPerformed

	private void keypad_2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_2ActionPerformed

	private void keypad_3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_3ActionPerformed

	private void keypad_4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_4ActionPerformed

	private void keypad_5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_5ActionPerformed

	private void keypad_6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_6ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_6ActionPerformed

	private void keypad_7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_7ActionPerformed

	private void keypad_8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_8ActionPerformed

	private void keypad_9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_9ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_9ActionPerformed

	private void keypad_0ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypad_0ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypad_0ActionPerformed

	private void keypadEnterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypadEnterActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypadEnterActionPerformed

	private void keypadCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypadCancelActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypadCancelActionPerformed

	private void keypadClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_keypadClearActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_keypadClearActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton atmSwitchButton;
	private javax.swing.JButton cardReaderEnter;
	private javax.swing.JTextField cardReaderField;
	private javax.swing.JLabel cardReaderLabel;
	private javax.swing.JPanel cardReaderPanel;
	private javax.swing.JLabel cashDispenser;
	private javax.swing.JLabel cashDispenserLabel;
	private javax.swing.JPanel cashDispenserPanel;
	private javax.swing.JButton depositSlotEnter;
	private javax.swing.JTextField depositSlotField;
	private javax.swing.JLabel depositSlotLabel;
	private javax.swing.JPanel depositSlotPanel;
	private javax.swing.JTextArea display;
	private javax.swing.JScrollPane displayScrollPane;
	private javax.swing.JPanel keypad;
	private javax.swing.JButton keypadCancel;
	private javax.swing.JButton keypadClear;
	private javax.swing.JButton keypadEnter;
	private javax.swing.JButton keypad_0;
	private javax.swing.JButton keypad_1;
	private javax.swing.JButton keypad_2;
	private javax.swing.JButton keypad_3;
	private javax.swing.JButton keypad_4;
	private javax.swing.JButton keypad_5;
	private javax.swing.JButton keypad_6;
	private javax.swing.JButton keypad_7;
	private javax.swing.JButton keypad_8;
	private javax.swing.JButton keypad_9;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JPanel maintenancePanel;
	private javax.swing.JLabel maintenancePanelDescription;
	private javax.swing.JTextField maintenancePanelField;
	private javax.swing.JLabel maintenancePanelLabel;
	private javax.swing.JLabel maintenancePanelState;
	private javax.swing.JTextArea receiptPrinter;
	private javax.swing.JLabel receiptPrinterLabel;
	private javax.swing.JPanel receiptPrinterPanel;
	private javax.swing.JScrollPane receiptPrinterScrollPane;
	private javax.swing.JLabel titleLabel;
	// End of variables declaration//GEN-END:variables
}
